development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: hacklab_episode_1_development
  pool: 5
  username: postgres
  password: postgres
  min_messages: WARNING

test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: hacklab_episode_1_test
  pool: 5
  username: postgres
  password: postgres
  min_messages: WARNING
